import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, AlignmentType, BorderStyle, SectionType, ShadingType, Table, TableRow, TableCell, WidthType, PageOrientation } from 'docx';
import { saveAs } from 'file-saver';
import type { Checklist, Question } from '@/types/checklist';

export type ExportOrientation = 'portrait' | 'landscape';

// ─── Strip HTML tags to plain text ───
function stripHtml(html: string): string {
 if (!html) return '';
 return html
.replace(/<br\s*\/?>/gi, '\n')
.replace(/<\/p>/gi, '\n')
.replace(/<\/li>/gi, '\n')
.replace(/<li>/gi, '• ')
.replace(/<[^>]*>/g, '')
.replace(/&nbsp;/g, ' ')
.replace(/&amp;/g, '&')
.replace(/&lt;/g, '<')
.replace(/&gt;/g, '>')
.replace(/&quot;/g, '"')
.replace(/&#39;/g, "'")
.replace(/\n{3,}/g, '\n\n')
.trim();
}

/** Strip leading number prefix like "1. " or "12. " from section titles */
function stripLeadingNumber(text: string): string {
 return text.replace(/^\s*\d+[\.\)]\s*/, '').trim();
}

// ─── Dynamic page constants ───
function getPageConstants(orientation: ExportOrientation) {
 const A4_W = orientation === 'landscape' ? 297 : 210;
 const A4_H = orientation === 'landscape' ? 210 : 297;
 const MARGIN = 15;
 const CONTENT_W = A4_W - MARGIN * 2;
 const LINE_H = 4.5;
 const PAGE_BOTTOM = A4_H - MARGIN - 10;

 const COL_NUM_W = CONTENT_W * 0.06;
 const COL_QUESTION_W = CONTENT_W * 0.42;
 const COL_RESPONSE_W = CONTENT_W * 0.24;
 const COL_EXPLAIN_W = CONTENT_W * 0.18;
 const COL_REF_W = CONTENT_W * 0.10;

 const COL_X_NUM = MARGIN;
 const COL_X_Q = COL_X_NUM + COL_NUM_W;
 const COL_X_RESP = COL_X_Q + COL_QUESTION_W;
 const COL_X_EXPL = COL_X_RESP + COL_RESPONSE_W;
 const COL_X_REF = COL_X_EXPL + COL_EXPLAIN_W;

 return { A4_W, A4_H, MARGIN, CONTENT_W, LINE_H, PAGE_BOTTOM, COL_NUM_W, COL_QUESTION_W, COL_RESPONSE_W, COL_EXPLAIN_W, COL_REF_W, COL_X_NUM, COL_X_Q, COL_X_RESP, COL_X_EXPL, COL_X_REF };
}

// ─── PDF Export ───

function addHeader(doc: jsPDF, title: string, pageNum: number, totalPages: number, c: ReturnType<typeof getPageConstants>) {
 doc.setFontSize(8);
 doc.setTextColor(100);
 doc.text(title, c.MARGIN, 12);
 doc.text(`Page ${pageNum} of ${totalPages}`, c.A4_W - c.MARGIN, 12, { align: 'right' });
 doc.setDrawColor(150);
 doc.line(c.MARGIN, 14, c.A4_W - c.MARGIN, 14);
}

function addFooter(doc: jsPDF, c: ReturnType<typeof getPageConstants>) {
 const y = c.A4_H - 10;
 doc.setFontSize(7);
 doc.setTextColor(120);
 doc.text('Generated by Luka AI', c.MARGIN, y);
 doc.setDrawColor(150);
 doc.line(c.MARGIN, y - 3, c.A4_W - c.MARGIN, y - 3);
}

function ensureSpace(doc: jsPDF, y: number, needed: number, c: ReturnType<typeof getPageConstants>): number {
 if (y + needed > c.PAGE_BOTTOM) {
 doc.addPage();
 return c.MARGIN + 8;
 }
 return y;
}

function getResponseLabel(question: Question): string {
 if (question.answer) {
 return stripHtml(question.answer);
 }
 return '';
}

function renderQuestionRowPDF(
 doc: jsPDF, question: Question, y: number, numbering: string, isSubQuestion: boolean, c: ReturnType<typeof getPageConstants>
): number {
 const plainText = stripHtml(question.text);
 const responseLabel = getResponseLabel(question);
 const explanationText = question.explanation ? stripHtml(question.explanation) : '';
 const refText = question.reference
 ? stripHtml(typeof question.reference === 'string' ? question.reference : (question.reference as any).name || '')
 : '';

 const fontSize = isSubQuestion ? 8.5 : 9;
 doc.setFontSize(fontSize);
 doc.setFont('helvetica', 'normal');

 const qLines = doc.splitTextToSize(plainText, c.COL_QUESTION_W - 2);
 const rLines = responseLabel ? doc.splitTextToSize(responseLabel, c.COL_RESPONSE_W - 2) : [];
 const eLines = explanationText ? doc.splitTextToSize(explanationText, c.COL_EXPLAIN_W - 2) : [];
 const refLines = refText ? doc.splitTextToSize(refText, c.COL_REF_W - 2) : [];

 const maxLines = Math.max(qLines.length, rLines.length, eLines.length, refLines.length, 1);
 const rowHeight = maxLines * c.LINE_H + 3;

 y = ensureSpace(doc, y, rowHeight + 4, c);

 // Light top border
 if (!isSubQuestion) {
 doc.setDrawColor(180);
 doc.setLineWidth(0.2);
 doc.line(c.MARGIN, y, c.MARGIN + c.CONTENT_W, y);
 y += 3;
 }

 // Number column
 doc.setFontSize(fontSize);
 doc.setTextColor(60);
 doc.setFont('helvetica', 'bold');
 const numX = isSubQuestion ? c.COL_X_NUM + 4 : c.COL_X_NUM;
 doc.text(numbering, numX + c.COL_NUM_W - 1, y + 1, { align: 'right' });

 // Question column
 doc.setFont('helvetica', 'normal');
 doc.setTextColor(0);
 doc.text(qLines, c.COL_X_Q + 1, y + 1);

 // Response column
 if (rLines.length) {
 doc.setTextColor(question.answer ? 30 : 100);
 doc.setFontSize(fontSize - 0.5);
 doc.text(rLines, c.COL_X_RESP + 1, y + 1);
 }

 // Explanation column
 if (eLines.length) {
 doc.setTextColor(80);
 doc.setFont('helvetica', 'italic');
 doc.setFontSize(fontSize - 1);
 doc.text(eLines, c.COL_X_EXPL + 1, y + 1);
 doc.setFont('helvetica', 'normal');
 }

 // Ref column
 if (refLines.length) {
 doc.setTextColor(0);
 doc.setFontSize(fontSize - 1);
 doc.text(refLines, c.COL_X_REF + 1, y + 1);
 }

 y += rowHeight;

 // Note
 if (question.note) {
 doc.setFontSize(7.5);
 doc.setTextColor(80);
 doc.setFont('helvetica', 'italic');
 const nLines = doc.splitTextToSize(`Note: ${stripHtml(question.note)}`, c.CONTENT_W - c.COL_NUM_W - 4);
 y = ensureSpace(doc, y, nLines.length * c.LINE_H, c);
 doc.text(nLines, c.COL_X_Q + 1, y);
 y += nLines.length * c.LINE_H;
 doc.setFont('helvetica', 'normal');
 }

 return y;
}

export function exportChecklistAsPDF(checklist: Checklist, orientation: ExportOrientation = 'portrait') {
 const c = getPageConstants(orientation);
 const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
 const title = stripHtml(checklist.title) || 'Checklist';

 // ─── Title page ───
 doc.setFontSize(22);
 doc.setTextColor(0);
 doc.setFont('helvetica', 'bold');
 doc.text(title, c.A4_W / 2, 80, { align: 'center' });

 if (checklist.description) {
 doc.setFontSize(12);
 doc.setTextColor(60);
 doc.setFont('helvetica', 'normal');
 const descLines = doc.splitTextToSize(stripHtml(checklist.description), c.CONTENT_W - 20);
 doc.text(descLines, c.A4_W / 2, 95, { align: 'center' });
 }

 if (checklist.objective) {
 doc.setFontSize(10);
 doc.setTextColor(80);
 const objLines = doc.splitTextToSize(`Objective: ${stripHtml(checklist.objective)}`, c.CONTENT_W - 20);
 doc.text(objLines, c.A4_W / 2, 115, { align: 'center' });
 }

 doc.setFontSize(9);
 doc.setTextColor(100);
 doc.text(`Generated: ${new Date().toLocaleDateString()}`, c.A4_W / 2, c.A4_H - 40, { align: 'center' });

 // ─── Content ───
 doc.addPage();
 let y = c.MARGIN + 8;

 checklist.sections.forEach((section, sIdx) => {
 const sectionNum = sIdx + 1;
 const sectionHeaderHeight = 12;
 y = ensureSpace(doc, y, sectionHeaderHeight + 20, c);

 if (sIdx > 0) {
 y += 6;
 y = ensureSpace(doc, y, sectionHeaderHeight + 20, c);
 }

 // Section header - black & white
 const sTitle = `${sectionNum}. ${stripLeadingNumber(stripHtml(section.title))}`;
 const sTitleLines = doc.splitTextToSize(sTitle, c.CONTENT_W - 8);
 const sHeaderH = sTitleLines.length * 6 + 6;

 doc.setFillColor(0, 0, 0);
 doc.roundedRect(c.MARGIN, y - 4, c.CONTENT_W, sHeaderH, 1.5, 1.5, 'F');

 doc.setFontSize(11);
 doc.setTextColor(255, 255, 255);
 doc.setFont('helvetica', 'bold');
 doc.text(sTitleLines, c.MARGIN + 4, y + 2);
 y += sHeaderH + 1;
 doc.setFont('helvetica', 'normal');

 // No column headers - removed

 // Questions
 section.questions.forEach((q, qIdx) => {
 const num = `${sectionNum}.${qIdx + 1}`;
 y = renderQuestionRowPDF(doc, q, y, num, false, c);

 if (q.subQuestions) {
 q.subQuestions.forEach((sq, sqIdx) => {
 const subNum = `${num}.${sqIdx + 1}`;
 y = renderQuestionRowPDF(doc, sq, y, subNum, true, c);

 if (sq.subQuestions) {
 sq.subQuestions.forEach((ssq, ssqIdx) => {
 const subSubNum = `${subNum}.${ssqIdx + 1}`;
 y = renderQuestionRowPDF(doc, ssq, y, subSubNum, true, c);
 });
 }
 });
 }
 });

 // Bottom border
 doc.setDrawColor(150);
 doc.setLineWidth(0.3);
 doc.line(c.MARGIN, y, c.MARGIN + c.CONTENT_W, y);
 y += 4;
 });

 // Headers/footers
 const totalPages = doc.getNumberOfPages();
 for (let i = 2; i <= totalPages; i++) {
 doc.setPage(i);
 addHeader(doc, title, i - 1, totalPages - 1, c);
 addFooter(doc, c);
 }

 doc.save(`${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
}

// ─── Word (DOCX) Export ───

function getWordConstants(orientation: ExportOrientation) {
 // A4 in DXA: portrait = 11906 x 16838, landscape swaps
 const pageW = orientation === 'landscape' ? 16838 : 11906;
 const pageH = orientation === 'landscape' ? 11906 : 16838;
 const marginDxa = 1134;
 const WORD_TOTAL = pageW - marginDxa * 2;
 const WORD_COL_NUM = Math.round(WORD_TOTAL * 0.06);
 const WORD_COL_Q = Math.round(WORD_TOTAL * 0.42);
 const WORD_COL_RESP = Math.round(WORD_TOTAL * 0.24);
 const WORD_COL_EXPL = Math.round(WORD_TOTAL * 0.18);
 const WORD_COL_REF = WORD_TOTAL - WORD_COL_NUM - WORD_COL_Q - WORD_COL_RESP - WORD_COL_EXPL;
 return { pageW, pageH, marginDxa, WORD_TOTAL, WORD_COL_NUM, WORD_COL_Q, WORD_COL_RESP, WORD_COL_EXPL, WORD_COL_REF };
}

const noBorders = {
 top: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
 bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
 left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
 right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
};

const topBorderOnly = {
 top: { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC' },
 bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
 left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
 right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
};

function buildQuestionTableRow(
 question: Question, numbering: string, isTopLevel: boolean, wc: ReturnType<typeof getWordConstants>
): TableRow {
 const plainText = stripHtml(question.text);
 const responseLabel = getResponseLabel(question);
 const explanationText = question.explanation ? stripHtml(question.explanation) : '';
 const refText = question.reference
 ? stripHtml(typeof question.reference === 'string' ? question.reference : (question.reference as any).name || '')
 : '';

 const borders = isTopLevel ? topBorderOnly : noBorders;
 const fontSize = 18;

 return new TableRow({
 children: [
 new TableCell({
 width: { size: wc.WORD_COL_NUM, type: WidthType.DXA },
 borders,
 children: [new Paragraph({
 spacing: { before: 40, after: 40 },
 children: [new TextRun({ text: numbering, bold: true, size: fontSize, font: 'Calibri', color: '333333' })],
 })],
 }),
 new TableCell({
 width: { size: wc.WORD_COL_Q, type: WidthType.DXA },
 borders,
 children: [new Paragraph({
 spacing: { before: 40, after: 40 },
 children: [new TextRun({ text: plainText, size: fontSize, font: 'Calibri', color: '000000' })],
 })],
 }),
 new TableCell({
 width: { size: wc.WORD_COL_RESP, type: WidthType.DXA },
 borders,
 children: [new Paragraph({
 spacing: { before: 40, after: 40 },
 children: [new TextRun({
 text: responseLabel || '',
 size: fontSize - 2,
 font: 'Calibri',
 color: question.answer ? '000000' : '666666',
 })],
 })],
 }),
 new TableCell({
 width: { size: wc.WORD_COL_EXPL, type: WidthType.DXA },
 borders,
 children: [new Paragraph({
 spacing: { before: 40, after: 40 },
 children: [new TextRun({
 text: explanationText,
 italics: true,
 size: fontSize - 2,
 font: 'Calibri',
 color: '444444',
 })],
 })],
 }),
 new TableCell({
 width: { size: wc.WORD_COL_REF, type: WidthType.DXA },
 borders,
 children: [new Paragraph({
 spacing: { before: 40, after: 40 },
 children: [new TextRun({
 text: refText,
 size: fontSize - 2,
 font: 'Calibri',
 color: '000000',
 })],
 })],
 }),
 ],
 });
}

export async function exportChecklistAsWord(checklist: Checklist, orientation: ExportOrientation = 'portrait') {
 const title = stripHtml(checklist.title) || 'Checklist';
 const wc = getWordConstants(orientation);

 const pageProps = {
 size: {
 width: orientation === 'landscape' ? 11906 : 11906,
 height: orientation === 'landscape' ? 16838 : 16838,
 orientation: orientation === 'landscape' ? PageOrientation.LANDSCAPE : PageOrientation.PORTRAIT,
 },
 margin: { top: wc.marginDxa, bottom: wc.marginDxa, left: wc.marginDxa, right: wc.marginDxa },
 };

 // Title page
 const titlePageChildren: Paragraph[] = [
 new Paragraph({ spacing: { before: 3000 }, children: [] }),
 new Paragraph({
 alignment: AlignmentType.CENTER,
 spacing: { after: 200 },
 children: [new TextRun({ text: title, bold: true, size: 48, font: 'Calibri', color: '000000' })],
 }),
 ];

 if (checklist.description) {
 titlePageChildren.push(new Paragraph({
 alignment: AlignmentType.CENTER,
 spacing: { after: 200 },
 children: [new TextRun({ text: stripHtml(checklist.description), size: 24, font: 'Calibri', color: '333333' })],
 }));
 }

 if (checklist.objective) {
 titlePageChildren.push(new Paragraph({
 alignment: AlignmentType.CENTER,
 spacing: { after: 200 },
 children: [new TextRun({ text: `Objective: ${stripHtml(checklist.objective)}`, size: 20, font: 'Calibri', color: '555555' })],
 }));
 }

 titlePageChildren.push(
 new Paragraph({ spacing: { before: 4000 }, children: [] }),
 new Paragraph({
 alignment: AlignmentType.CENTER,
 children: [new TextRun({ text: `Generated: ${new Date().toLocaleDateString()}`, size: 18, font: 'Calibri', color: '888888' })],
 })
 );

 // Content
 const contentChildren: (Paragraph | Table)[] = [];

 checklist.sections.forEach((section, sIdx) => {
 const sectionNum = sIdx + 1;

 // Section header - black & white
 contentChildren.push(new Paragraph({
 spacing: { before: sIdx === 0 ? 100 : 360, after: 100 },
 shading: { type: ShadingType.CLEAR, color: 'auto', fill: '000000' },
 children: [new TextRun({ text: `${sectionNum}. ${stripLeadingNumber(stripHtml(section.title))}`, bold: true, size: 26, font: 'Calibri', color: 'FFFFFF' })],
 }));

 // Build table rows - NO header row
 const rows: TableRow[] = [];

 section.questions.forEach((q, qIdx) => {
 const num = `${sectionNum}.${qIdx + 1}`;
 rows.push(buildQuestionTableRow(q, num, true, wc));

 if (q.subQuestions) {
 q.subQuestions.forEach((sq, sqIdx) => {
 const subNum = `${num}.${sqIdx + 1}`;
 rows.push(buildQuestionTableRow(sq, subNum, false, wc));

 if (sq.subQuestions) {
 sq.subQuestions.forEach((ssq, ssqIdx) => {
 const subSubNum = `${subNum}.${ssqIdx + 1}`;
 rows.push(buildQuestionTableRow(ssq, subSubNum, false, wc));
 });
 }
 });
 }
 });

 if (rows.length > 0) {
 contentChildren.push(new Table({
 width: { size: 100, type: WidthType.PERCENTAGE },
 rows,
 }));
 }
 });

 const doc = new Document({
 creator: 'Luka AI',
 title,
 description: checklist.description ? stripHtml(checklist.description) : '',
 sections: [
 { properties: { page: pageProps }, children: titlePageChildren },
 { properties: { type: SectionType.NEXT_PAGE, page: pageProps }, children: contentChildren as any },
 ],
 });

 const blob = await Packer.toBlob(doc);
 saveAs(blob, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.docx`);
}
